console.log("hello");
console.log("hello");
try{
    console.log(s)//if there is error in try block then 
    //catch is executed ignoring the error
}
catch{
    console.log("catch an error..a is undefined")
}//if catch has error then no solution

console.log("hello");
console.log("hello");

console.log("hello");

//all log will be print after catch statement is sucessfully executed
